services:
  - type: web
    name: my-flask-app
    env: python
    region: oregon
    buildCommand: ./build.sh
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 Map:app
    pythonVersion: 3.8
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/serviceAccountKey.json  # Path where Render stores the secret file
      - key: FLASK_ENV
        value: production
